[build]
  command = "NODE_ENV=production NODE_OPTIONS=--openssl-legacy-provider npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
